Fix exception
SKIP: versioncontrol/tests/functional.py (no svn bindings)
Traceback (most recent call last):
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/rjollos/.pyenv/versions/3.8.6/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/rjollos/Documents/Workspace/trac-dev/trac-py3/trac/test.py", line 265, in run
    self.setUp()
  File "/Users/rjollos/Documents/Workspace/trac-dev/trac-py3/trac/tests/functional/__init__.py", line 136, in setUp
    self._testenv = self.env_class(env_path, server_port, baseurl)
  File "/Users/rjollos/Documents/Workspace/trac-dev/trac-py3/trac/tests/functional/testenv.py", line 80, in __init__
    self.create()
  File "/Users/rjollos/Documents/Workspace/trac-dev/trac-py3/trac/tests/functional/testenv.py", line 153, in create
    self._tracadmin('initenv', self.tracdir, self.dburi,
  File "/Users/rjollos/Documents/Workspace/trac-dev/trac-py3/trac/tests/functional/testenv.py", line 268, in _tracadmin
    self.logfile.write(proc.stderr)
TypeError: a bytes-like object is required, not 'NoneType'